appVersion=1.0.0

springBootVersion=4.1.0
springDependencyManagementVersion=1.1.7
swaggerAnnotationsVersion=2.2.15

protobufGradlePluginVersion=0.10.0
protobufVersion=4.34.2
grpcVersion=1.80.0

flywayVersion=11.0.0

pengradTelegramBotApiVersion=10.1.0

restAssuredVersion=6.0.0

awaitilityVersion=4.2.2
wiremockVersion=3.13.0
archunitVersion=1.4.2

jacocoVersion=0.8.13

spotlessVersion=8.9.0
palantirJavaFormatVersion=2.71.0